name: mozilla-sec-eia
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  # Packages required for setting up the environment
  - pip>=21,<24
  - python>=3.10,<=3.12
  - setuptools>=66,<69

  # Packages specified in setup.py that need or benefit from binary conda packages
  # - geopandas>=0.9,<0.11
  # - pygeos>=0.10,<0.13  # Python wrappers for the GEOS spatial libraries
  # - python-snappy>=0.6,<0.7  # Supports snappy compression in pyarrow/parquet
  # - cramjam>=2.6  # Supports snappy compression w/o system library install

  # Packages not specified in setup.py that provide optional, helpful binaries:
  # - numba>=0.55.1,<0.57  # numba speeds up some kinds of math by 100x

  # Jupyter packages:
  - jupyterlab>=3.2,<4
  - nbconvert>=6,<7 # Used to clear notebook outputs in pre-commit hooks

  # These are not normal Python packages available on PyPI
  - nodejs # Useful for Jupyter and prettier pre-commit hook

  - cpuonly
  - pytorch>=2.2,<3
  - torchvision

  # GDAL is a transitive dependency whose binaries must match those installed by the
  # pudl-dev conda environment, so we also install it with conda here.
  - gdal==3.9.3 # pinned to ensure it matches pudl-dev environment exactly.

  # Use pip to install the package defined by this repo for development:
  - pip:
      - --editable ./[dev,docs,tests,types]
