services:
  # This service runs the postgres DB used by dagster for run storage, schedule storage,
  # and event log storage.
  dagster_postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    networks:
      - dagster

  dagster_pudl_models:
    build:
      context: ../../
      dockerfile: ./docker/deployment/Dockerfile
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      GCS_FILINGS_BUCKET_NAME: "2de2b9f52c99a240-bucket-sec-10ks"
      GCS_LABELS_BUCKET_NAME: "labeled-ex21-filings"
      GCS_METADATA_DB_INSTANCE_CONNECTION: "catalyst-cooperative-mozilla:us-central1:pg-mozilla"
      GCS_METADATA_DB_NAME: "postgres"
      GCS_IAM_USER: "mozilla-dev-sa@catalyst-cooperative-mozilla.iam.gserviceaccount.com"
      MLFLOW_TRACKING_URI: "https://mlflow-ned2up6sra-uc.a.run.app"
      GCS_PROJECT: "catalyst-cooperative-mozilla"
    networks:
      - dagster

networks:
  dagster:
    driver: bridge
